### ISSUE TITLE
Wrap long lines in HTML

### ISSUE THREAD

**Issue by griffinlacek** [werewolfe/prj-rev-bwfs-dasmoto#3]
Just a minor code styling suggestion. It's good practice to wrap long lines of code to ~80 characters so that we can see all the code in the window without scrolling. Something to keep in mind!

https://github.com/werewolfe/prj-rev-bwfs-dasmoto/blob/master/ArtStore/index.html#L16
https://github.com/werewolfe/prj-rev-bwfs-dasmoto/blob/master/ArtStore/index.html#L23
https://github.com/werewolfe/prj-rev-bwfs-dasmoto/blob/master/ArtStore/index.html#L30

**Comment by werewolfe** [comment]
Thanks for this suggestion. I was able to set this up in my IDE. I appreciate all of your feedback!
